# -*- coding: utf-8 -*-
"""Bài Tập Thực Hành Trực Quan Hóa Dữ Liệu: COVID-19 tại Đông Nam Á

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19QttW_95FwsZqjpJWGmr-Wc1f_31o17o

# Bài Tập Thực Hành Trực Quan Hóa Dữ Liệu: COVID-19 tại Đông Nam Á

## Chuẩn bị Dữ liệu (Data Preparation)

Hãy chạy đoạn code sau để tự động lấy dữ liệu từ Our World in Data, lọc các quốc gia Đông Nam Á và xử lý sơ bộ các giá trị thiếu (NaN).
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Cài đặt style chung cho Seaborn
sns.set_theme(style="whitegrid")

# 1. Tải dữ liệu trực tiếp từ Our World in Data (có thể mất 1-2 phút)
url = 'https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv'
print("Đang tải dữ liệu...")
df_raw = pd.read_csv(url)

df_raw

# 2. Lọc dữ liệu khu vực Đông Nam Á & Giới hạn thời gian (2021 - 2022)
asean_countries = ['Vietnam', 'Thailand', 'Indonesia', 'Malaysia', 'Singapore', 'Philippines']
df = df_raw[df_raw['location'].isin(asean_countries)].copy()

df['date'] = pd.to_datetime(df['date'])
df = df[(df['date'] >= '2021-01-01') & (df['date'] <= '2022-12-31')]

# 3. Lọc ra các cột quan trọng cần thiết cho bài tập
cols_to_keep = [
    'location', 'date', 'new_cases', 'new_deaths',
    'new_tests', 'total_vaccinations', 'people_fully_vaccinated_per_hundred'
]
df = df[cols_to_keep]

# 4. Xử lý NaN cơ bản (Điền 0 cho ca mắc/tử vong/test mới; fill forward cho vaccine vì là số liệu tích lũy)
df[['new_cases', 'new_deaths', 'new_tests']] = df[['new_cases', 'new_deaths', 'new_tests']].fillna(0)
df['total_vaccinations'] = df.groupby('location')['total_vaccinations'].ffill().fillna(0)
df['people_fully_vaccinated_per_hundred'] = df.groupby('location')['people_fully_vaccinated_per_hundred'].ffill().fillna(0)

print(df.head())

"""Hãy sử dụng `matplotlib` và `seaborn` để trả lời các câu hỏi bằng biểu đồ. Dữ liệu đang nằm trong biến `df`.

## Câu 1: Phân phối cơ bản (Histogram)
**Bối cảnh:** Trước khi so sánh các nước, ta cần biết quy mô lây nhiễm hàng ngày trong khu vực phân bổ như thế nào.
* **Yêu cầu:** Vẽ **Histogram** cho cột `new_cases`.
* **Hint:** Số ca mắc có ngày bằng 0, có ngày lên tới hàng chục ngàn. Hàm `sns.histplot(bins=50)` sẽ giúp bạn thấy dữ liệu bị lệch (skewed) về bên nào.
"""

plt.figure(figsize=(10,6))
sns.histplot(df['new_cases'], bins=50, kde=True)
plt.title('Phân phối số ca mắc mới (new_cases)')
plt.xlabel('Số ca mắc')
plt.ylabel('Tần suất')
plt.show()

"""## Câu 2: Biến động theo thời gian (Line Chart)
**Bối cảnh:** Biểu đồ ở Câu 1 không cho ta thấy dịch bùng phát *khi nào*. Hãy thêm yếu tố thời gian.
* **Yêu cầu:** Vẽ **Line Chart** thể hiện xu hướng `new_cases` theo `date` của từng quốc gia.
* **Hint:** Sử dụng `sns.lineplot()`. Truyền `x='date'`, `y='new_cases'` và phân loại màu sắc bằng `hue='location'`.
"""

plt.figure(figsize=(12,6))
sns.lineplot(data=df, x='date', y='new_cases', hue='location')
plt.title('Số ca mắc theo thời gian')
plt.xlabel('Ngày')
plt.ylabel('Số ca mắc')
plt.legend(title='Quốc gia')
plt.show()

"""## Câu 3: Tổng kết mất mát (Bar Chart)
**Bối cảnh:** Dịch bệnh bùng phát mạnh (Câu 2), vậy tổng thiệt hại về nhân mạng của mỗi quốc gia là bao nhiêu?
* **Yêu cầu:** Dùng **Bar Chart** để vẽ Tổng số ca tử vong (`new_deaths`) của mỗi nước trong giai đoạn này.
* **Hint:** Bạn không thể vẽ trực tiếp từ `df`. Hãy tạo một DataFrame mới bằng cách dùng `.groupby('location')['new_deaths'].sum().reset_index()`, sau đó dùng `sns.barplot()`.
"""

df_deaths = df.groupby('location')['new_deaths'].sum().reset_index()

plt.figure(figsize=(8,5))
sns.barplot(data=df_deaths, x='location', y='new_deaths')
plt.title('Tổng số ca tử vong')
plt.xlabel('Quốc gia')
plt.ylabel('Số ca tử vong')
plt.show()

"""## Câu 4: Phân bổ nỗ lực phòng dịch (Pie Chart)
**Bối cảnh:** Để đối phó với số ca tử vong ở Câu 3, các nước bắt đầu chiến dịch tiêm chủng. Nước nào chiếm tỷ trọng số liều vaccine lớn nhất trong nhóm?
* **Yêu cầu:** Vẽ **Pie Chart** thể hiện tỷ trọng tổng số liều vaccine (`total_vaccinations`) đã tiêm của từng nước.
* **Hint (Rất quan trọng):** `total_vaccinations` là *dữ liệu cộng dồn*. Bạn **không được** dùng `.sum()`. Hãy dùng `.groupby('location')['total_vaccinations'].max()` để lấy con số cuối cùng lớn nhất của mỗi nước. Dùng `plt.pie()` để vẽ.
"""

df_vac = df.groupby('location')['total_vaccinations'].max()

plt.figure(figsize=(7,7))
plt.pie(df_vac, labels=df_vac.index, autopct='%1.1f%%')
plt.title('Tỷ trọng số liều vaccine')
plt.show()

"""## Câu 5: Đo lường sự bất ổn (Box Plot)
**Bối cảnh:** Việc tiêm chủng (Câu 4) bắt đầu làm thay đổi cục diện. Quốc gia nào có số ca mắc mới mỗi ngày biến động khó lường nhất (nhiều outliers nhất)?
* **Yêu cầu:** Vẽ **Box Plot** so sánh sự phân tán của `new_cases` giữa các nước.
* **Hint:** Dùng `sns.boxplot(x='location', y='new_cases')`. Chú ý những điểm chấm đen ngoài râu (whiskers) biểu thị những ngày "đỉnh dịch" (outliers).
"""

plt.figure(figsize=(10,6))
sns.boxplot(data=df, x='location', y='new_cases')
plt.title('Phân bố ca mắc theo quốc gia')
plt.xlabel('Quốc gia')
plt.ylabel('Số ca mắc')
plt.show()

"""## Câu 6: Năng lực y tế và lây nhiễm (Scatter Plot)
**Bối cảnh:** Liệu số ca mắc nhiều (Câu 5) có phải chỉ đơn thuần là do nước đó xét nghiệm nhiều?
* **Yêu cầu:** Vẽ **Scatter Plot** để xem xét mối quan hệ giữa số xét nghiệm (`new_tests`) và ca mắc mới (`new_cases`).
* **Hint:** Dùng `sns.scatterplot()`. Vì có rất nhiều ngày số xét nghiệm là 0 (do không báo cáo), bạn có thể lọc các dòng `df['new_tests'] > 0` trước khi vẽ để biểu đồ không bị nhiễu.
"""

df_test = df[df['new_tests'] > 0]

plt.figure(figsize=(8,6))
sns.scatterplot(data=df_test, x='new_tests', y='new_cases', hue='location')
plt.title('Test vs Ca mắc')
plt.xlabel('Số test')
plt.ylabel('Số ca mắc')
plt.show()

"""## Câu 7: Bức tranh toàn cảnh (Heatmap)
**Bối cảnh:** Đến đây, ta có 4 yếu tố chính: Ca mắc, Ca tử vong, Xét nghiệm, Tỷ lệ tiêm chủng. Chúng tác động qua lại với nhau như thế nào?
* **Yêu cầu:** Vẽ **Heatmap** thể hiện ma trận tương quan giữa 4 cột: `new_cases`, `new_deaths`, `new_tests`, và `people_fully_vaccinated_per_hundred`.
* **Hint:** Lọc ra 4 cột trên, dùng `.corr()` để tạo ma trận toán học, sau đó đưa vào `sns.heatmap(annot=True, cmap='coolwarm')`.
"""

corr = df[['new_cases', 'new_deaths', 'new_tests',
           'people_fully_vaccinated_per_hundred']].corr()

plt.figure(figsize=(8,6))
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title('Ma trận tương quan')
plt.show()

"""## Câu 8: Chứng minh hiệu quả Vắc-xin (Linear Regression Plot)
**Bối cảnh:** Từ Heatmap ở Câu 7, hãy đi sâu vào mối quan hệ quan trọng nhất: Tỷ lệ tiêm chủng cao có thực sự giúp giảm ca tử vong mới không?
* **Yêu cầu:** Vẽ biểu đồ hồi quy **Linear Regression Plot** với trục X là `people_fully_vaccinated_per_hundred` và trục Y là `new_deaths`.
* **Hint:** Dùng `sns.regplot()`. Đường thẳng (trendline) sẽ cho bạn biết xu hướng chung của dữ liệu thực tế.
"""

plt.figure(figsize=(8,6))
sns.regplot(data=df,
            x='people_fully_vaccinated_per_hundred',
            y='new_deaths',
            scatter_kws={'alpha':0.3})
plt.title('Tỷ lệ tiêm vs tử vong')
plt.xlabel('Tỷ lệ tiêm (%)')
plt.ylabel('Số ca tử vong')
plt.show()