# -*- coding: utf-8 -*-
"""Exercise-Pie-Charts-Box-Plots-Scatter-Plots-and-Bubble-Plots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mxsU8SXrEW7qWupNcO_sx9yoaPt8ivAq
"""

import numpy as np
import pandas as pd

# install xlrd
!pip install xlrd

print('xlrd installed!')

# Đọc dữ liệu từ file CSV:
df_can = pd.read_excel('/content/Canada-1.xlsx',
                   sheet_name='Canada by Citizenship',
                       skiprows=range(20),
                      )
# # Tải dữ liệu từ URL
# url = "_______"
# df = pd.read_csv(url)

df_can

df_can.shape

1. Clean up the dataset to remove columns that are not informative

df_can.drop(['AREA', 'REG', 'DEV', 'Type', 'Coverage'], axis=1, inplace=True) # Remove column
df_can.head()

"""2. Rename some of the columns so that they make sense."""

df_can.rename(columns={'OdName':'Country', 'AreaName':'Continent','RegName':'Region'}, inplace=True)
print(df_can.head())

"""3. For consistency, ensure that all column labels of type string."""

# let's examine the types of the column labels
all(isinstance(column, str) for column in df_can.columns)
#check data type
df_can.dtypes

df_can.columns = list(map(str, df_can.columns))

# let's check the column labels types now
all(isinstance(column, str) for column in df_can.columns)
df_can.dtypes

df_can.set_index('Country', inplace=True)

# let's view the first five elements and see how the dataframe was changed
df_can.head()

df_can.columns = list(map(str, df_can.columns))
df_can.columns

years_int = list(range(1980, 2014)) # list years, type = int
years_str = list(map(str, years_int)) # Convert int to str
print(years_int)
print("=" * 1000)
print(years_str)

df_can[years_str].head()

# Add total column
df_can['Total'] = df_can[years_str].sum(axis=1)
print(df_can)

# let's check the column labels types now
all(isinstance(column, str) for column in df_can.columns)

# Clean non country row
drop_row = ['Total', 'Unknown']
df_can.drop(drop_row, axis=0, inplace=True)
print(df_can)

# finally, let's create a list of years from 1980 - 2013
years = list(map(str, range(1980, 2014)))
years

df_can[years].sum(axis=1)

df_can['Total'] = df_can[years].sum(axis=1)

# let's view the first five elements and see how the dataframe was changed
df_can

continent_list = df_can.groupby('Continent').sum()
continent_list

# continent_list = df_can.groupby('Continent').sum()['Total']           # Series
# continent_list

df_continent = df_can.groupby('Continent').sum()[['Total']]           # Dataframe
df_continent

df_continent['Total'].plot(kind='pie', subplots= True)

df_continent = df_can.groupby('Continent').sum()
df_continent

df_continent['2013'].plot(kind='pie')

df_continent[list(map(str, range(2010, 2014)))].plot(kind='pie', subplots=True, figsize=(40, 20))

# Commented out IPython magic to ensure Python compatibility.
# use the inline backend to generate the plots within the browser
# %matplotlib inline

import matplotlib as mpl
import matplotlib.pyplot as plt

mpl.style.use('ggplot') # optional: for ggplot-like style

# check for latest version of Matplotlib
print ('Matplotlib version: ', mpl.__version__) # >= 2.0.0